FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine AS base

WORKDIR /app

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine AS build
WORKDIR /app
ENV BAGET_ENV=stage

COPY ./src ./src
COPY ./test ./test

WORKDIR /app/test

ENTRYPOINT ["dotnet", "test" , "MatchingTest.csproj"]
