FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine
RUN apk update && apk add bash

# Required inside Docker, otherwise file-change events may not trigger
ENV DOTNET_USE_POLLING_FILE_WATCHER 1
ENV BAGET_ENV=stage
