version: 0.0
os: linux
files:
  - source: docker-compose-matching.yml
    destination: /home/ubuntu/
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/setup.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/stop.sh
      timeout: 300
      runas: root
    - location: scripts/start.sh
      timeout: 300
      runas: root

